"""Index on file path

Revision ID: cac7d9b1fa9d
Revises: 586c4ce5bbe0
Create Date: 2025-07-14 19:13:51.864743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac7d9b1fa9d'
down_revision: Union[str, Sequence[str], None] = '586c4ce5bbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_file_path'), 'documents', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_path'), table_name='documents')
    # ### end Alembic commands ###
