apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
  namespace: note-rags
spec:
  selector:
    app: notes-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP